data:
  videos_dir: /teamspace/studios/this_studio/lightning-action/data/videos  # MP4 directory
  labels_dir: /teamspace/studios/this_studio/lightning-action/data/labels_numpy  # Numpy directory
  expt_ids:
  - 1.1.28R
  - 1.1.28L
  - 1.2.2R
  - 1.2.28R
  - 1.3.1R
  - 1.4.1R
  - 2.1.28L
  - 3.1.28L
  - 3.2.28L
  ignore_index: -100
  seed: 42
model:
  backbone: dtcn
  dropout_rate: 0.1
  input_size: 1536
  num_hid_units: 32
  num_lags: 2
  num_layers: 4
  output_size: 3
  seed: 42
  encoder_checkpoint: /teamspace/studios/this_studio/lightning-action/data/checkpoints/encoder/vitm.ckpt
  encoder_config_path: /teamspace/studios/this_studio/lightning-action/configs/vit_mae/vit_m-betta.yaml
  freeze_encoder: true
optimizer:
  T_max: 200
  lr: .001
  type: Adam
  scheduler:
    use_scheduler: true
    type: CosineAnnealingWarmRestarts
    T_0: 34
    T_mult: 2
    eta_min_factor: 20
training:
  checkpointing: true
  batch_size: 2  
  device: gpu
  early_stopping: false
  early_stopping_patience: 20
  num_epochs: 160
  num_workers: 4
  sequence_length: 500
  train_probability: 1.0
  val_probability: 0.0
