# Example configuration for action segmentation training
# This config demonstrates the structure and parameters for training
# a basic segmentation model with the lightning-action framework

# Data configuration
data:
  # Dataset configuration
  data_path: /path/to/dataset

  input_dir: markers

  # Specify subset of ids in data_path for model training; null will default to all
  expt_ids: null

  # Reproducibility for data splits
  seed: 42

  # Set to -100 if every single frame is scored; see docs for more info
  ignore_index: 0
  weight_classes: true

# Model configuration
model:

  input_size: 10
  output_size: 4

  # Backbone architecture [temporalmlp | lstm | gru | dtcn]
  backbone: temporalmlp
  
  # Backbone parameters
  num_hid_units: 256
  num_layers: 2
  num_lags: 2
  
  # Reproducibility for model initialization
  seed: 42

# Optimizer configuration
optimizer:
  type: Adam  # Adam or AdamW
  lr: 1e-3
  wd: 1e-4  # weight decay
  
  # Learning rate scheduler (optional)
  scheduler: cosine  # 'step', 'cosine', or null

  # For step scheduler:
  step_size: 30
  gamma: 0.1

  # For cosine scheduler:
  T_max: 100

# Training configuration
training:

  device: cpu

  # Training parameters
  num_epochs: 100
  log_every_n_steps: 10
  check_val_every_n_epoch: 1

  # DataLoader parameters
  sequence_length: 500
  batch_size: 32
  num_workers: 4
  train_probability: 0.9
  val_probability: 0.1
